#!/bin/bash
#
# Copyright (C) 2012 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Stop if something fails.
set -e

mkdir classes

if [ ${USE_JACK} = "true" ]; then
  ${JACK} --output-jack src.jack src

  ${JASMIN} -d classes src/*.j
  ${JILL} classes --output jasmin.jack

  # We set jack.import.type.policy=keep-first to consider class definitions from jasmin first.
  ${JACK} --import jasmin.jack --import src.jack -D jack.import.type.policy=keep-first --output-dex .
else
  ${JAVAC} -d classes src/*.java
  ${JASMIN} -d classes src/*.j

  ${DX} --debug --dex --dump-to=classes.lst --output=classes.dex classes
fi
zip $TEST_NAME.jar classes.dex
