#!/bin/bash
#
# Copyright (C) 2014 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Stop if something fails.
set -e

mkdir classes

# All except Main
${JAVAC} -d classes `find src -name '*.java'`
rm classes/MirandaInterface.class
${DX} -JXmx256m --debug --dex --dump-to=classes.lst --output=classes.dex classes

# Only Main
${JAVAC} -d classes `find src -name '*.java'`
rm classes/Main.class classes/MirandaAbstract.class classes/MirandaClass*.class classes/MirandaInterface2*.class
${DX} -JXmx256m --debug --dex --dump-to=classes2.lst --output=classes2.dex classes

zip $TEST_NAME.jar classes.dex classes2.dex
