#!/bin/bash
#
# Copyright 2015 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# make us exit on a failure
set -e

# Generate the smali Main.smali file or fail
${ANDROID_BUILD_TOP}/art/test/utils/python/generate_smali_main.py ./smali

# Should we compile with Java source code. By default we will use Smali.
USES_JAVA_SOURCE="false"
if [[ $ARGS == *"--jvm"* ]]; then
  USES_JAVA_SOURCE="true"
elif [[ "$USE_JACK" == "true" ]]; then
  if $JACK -D jack.java.source.version=1.8 >& /dev/null; then
    USES_JAVA_SOURCE="true"
  else
    echo "WARNING: Cannot use jack because it does not support JLS 1.8. Falling back to smali" >&2
  fi
fi

if [[ "$USES_JAVA_SOURCE" == "true" ]]; then
  # We are compiling java code, create it.
  mkdir -p src
  ${ANDROID_BUILD_TOP}/art/tools/extract-embedded-java ./smali ./src
  # Ignore the smali directory.
  EXTRA_ARGS="--no-smali"
fi

./default-build "$@" "$EXTRA_ARGS" --experimental default-methods
