#!/bin/bash
#
# Copyright (C) 2014 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ensure flags includes prebuild and relocate. It doesn't make sense unless we
# have a oat file we want to relocate.
# TODO Unfortunately we have no way to force prebuild on for both host and target (or skip if not on).
flags="${@/--relocate/}"
flags="${flags/--no-relocate/}"
flags="${flags} --relocate"

# Make sure we can run without relocation
echo "Run without dex2oat/patchoat"
# /bin/false is actually not even there for either, so the exec will fail.
# Unfortunately there is no equivalent to /bin/false in android.
${RUN} ${flags} --runtime-option -Xnodex2oat

# Make sure we can run with the oat file.
echo "Run with dexoat/patchoat"
${RUN} ${flags} --runtime-option -Xdex2oat

# Make sure we can run with the default settings.
echo "Run default"
${RUN} ${flags}
