#!/bin/bash
#
# Copyright 2015 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# make us exit on a failure
set -e

# TODO: Support running with jack.

if [[ $@ == *"--jvm"* ]]; then
  # Build the Java files if we are running a --jvm test
  mkdir -p src
  mkdir -p classes
  ${ANDROID_BUILD_TOP}/art/tools/extract-embedded-java ./smali ./src
  # Build with the non-conflicting version
  ${JAVAC} -implicit:none -d classes src/Iface.java build-src/Iface2.java src/Main.java
  rm classes/Iface2.class
  # Build with the conflicting version
  ${JAVAC} -implicit:none -cp classes -d classes src/Iface2.java
else
  ./default-build "$@" --experimental default-methods
fi
