#!/bin/bash
#
# Copyright (C) 2008 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Stop if something fails.
set -e

DX_FLAGS=""

while true; do
  if [ "x$1" = "x--dx-option" ]; then
    shift
    option="$1"
    DX_FLAGS="${DX_FLAGS} $option"
    shift
  elif expr "x$1" : "x--" >/dev/null 2>&1; then
    echo "unknown $0 option: $1" 1>&2
    exit 1
  else
    break
  fi
done

if [ -e classes.dex ]; then
  zip $TEST_NAME.jar classes.dex
  exit 0
fi

mkdir classes
${JAVAC} -d classes `find src -name '*.java'`

if [ -d src2 ]; then
  ${JAVAC} -d classes `find src2 -name '*.java'`
fi

if [ ${NEED_DEX} = "true" ]; then
  ${DX} -JXmx256m --debug --dex --dump-to=classes.lst --output=classes.dex \
    --dump-width=1000 ${DX_FLAGS} classes
fi

if [ -d smali ]; then
  # Compile Smali classes
  ${SMALI} -JXmx256m --output smali_classes.dex `find smali -name '*.smali'`
  ${DXMERGER} classes.dex classes.dex smali_classes.dex
fi

if [ -d src-ex ]; then
  mkdir classes-ex
  ${JAVAC} -d classes-ex -cp classes `find src-ex -name '*.java'`
  if [ ${NEED_DEX} = "true" ]; then
    ${DX} -JXmx256m --debug --dex --dump-to=classes-ex.lst --output=classes-ex.dex \
      --dump-width=1000 ${DX_FLAGS} classes-ex

    # quick shuffle so that the stored name is "classes.dex"
    mv classes.dex classes-1.dex
    mv classes-ex.dex classes.dex
    zip $TEST_NAME-ex.jar classes.dex
    mv classes.dex classes-ex.dex
    mv classes-1.dex classes.dex
  fi
fi

if [ ${NEED_DEX} = "true" ]; then
  zip $TEST_NAME.jar classes.dex
fi
