#!/bin/bash
#
# Copyright (C) 2014 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Stop if something fails.
set -e

# Write out the source file.
mkdir src
python ./genMain.py

# Increase the file size limitation for classes.lst as the machine generated
# source file contains a lot of methods and is quite large.

# Jack generates big temp files so only apply ulimit for dx.
if [ ${USE_JACK} = "false" ]; then
  ulimit -S 4096
fi

./default-build
