#!/bin/bash
#
# Copyright 2015 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# make us exit on a failure
set -e

# We will be making more files than the ulimit is set to allow. Remove it temporarily.
OLD_ULIMIT=`ulimit -S`
ulimit -S unlimited

restore_ulimit() {
  ulimit -S "$OLD_ULIMIT"
}
trap 'restore_ulimit' ERR

# Generate the smali files and expected.txt or fail
./util-src/generate_smali.py ./smali ./expected.txt

# Should we compile with Java source code. By default we will use Smali.
USES_JAVA_SOURCE="false"
if [[ $@ == *"--jvm"* ]]; then
  USES_JAVA_SOURCE="true"
elif [[ "$USE_JACK" == "true" ]]; then
  if $JACK -D jack.java.source.version=1.8 2>/dev/null; then
    USES_JAVA_SOURCE="true"
  else
    echo "WARNING: Cannot use jack because it does not support JLS 1.8. Falling back to smali" >&2
  fi
fi

if [[ "$USES_JAVA_SOURCE" == "true" ]]; then
  # We are compiling java code, create it.
  mkdir -p src
  ${ANDROID_BUILD_TOP}/art/tools/extract-embedded-java ./smali ./src
  # Ignore the smali directory.
  EXTRA_ARGS="--no-smali"
fi

./default-build "$@" "$EXTRA_ARGS" --experimental default-methods

# Reset the ulimit back to its initial value
restore_ulimit
