#!/bin/bash
#
# Copyright (C) 2014 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Stop if something fails.
set -e

# All except Main
mkdir classes
${JAVAC} -d classes `find src -name '*.java'`
rm classes/Main.class

# Only Main
mkdir classes2
${JAVAC} -d classes2 `find src -name '*.java'`
rm classes2/Second.class classes2/FillerA.class classes2/FillerB.class classes2/Inf*.class

if [ ${USE_JACK} = "true" ]; then
  # Create .jack files from classes generated with javac.
  ${JILL} classes --output classes.jack
  ${JILL} classes2 --output classes2.jack

  # Create DEX files from .jack files.
  ${JACK} --import classes.jack --output-dex .
  mv classes.dex classes-1.dex
  ${JACK} --import classes2.jack --output-dex .
  mv classes.dex classes2.dex
  mv classes-1.dex classes.dex
else
  # All except Main
  ${DX} -JXmx256m --debug --dex --dump-to=classes.lst --output=classes.dex classes

  # Only Main
  ${DX} -JXmx256m --debug --dex --dump-to=classes2.lst --output=classes2.dex classes2
fi
zip $TEST_NAME.jar classes.dex classes2.dex
