#!/bin/bash
#
# Copyright (C) 2014 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Stop if something fails.
set -e

mkdir classes
${JAVAC} -d classes `find src -name '*.java'`

mkdir classes-ex
mv classes/Super.class classes-ex

if [ ${USE_JACK} = "true" ]; then
  # Create .jack files from classes generated with javac.
  ${JILL} classes --output classes.jack
  ${JILL} classes-ex --output classes-ex.jack

  # Create DEX files from .jack files.
  ${JACK} --import classes.jack --output-dex .
  zip $TEST_NAME.jar classes.dex
  ${JACK} --import classes-ex.jack --output-dex .
  zip ${TEST_NAME}-ex.jar classes.dex
else
  if [ ${NEED_DEX} = "true" ]; then
    ${DX} -JXmx256m --debug --dex --dump-to=classes.lst --output=classes.dex --dump-width=1000 classes
    zip $TEST_NAME.jar classes.dex
    ${DX} -JXmx256m --debug --dex --dump-to=classes-ex.lst --output=classes.dex --dump-width=1000 classes-ex
    zip ${TEST_NAME}-ex.jar classes.dex
  fi
fi
