/*
 * Copyright (C) 2012 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "asm_support_x86_64.S"

    /*
     * Portable invocation stub.
     */
UNIMPLEMENTED art_portable_invoke_stub

UNIMPLEMENTED art_portable_proxy_invoke_handler

UNIMPLEMENTED art_portable_resolution_trampoline

UNIMPLEMENTED art_portable_to_interpreter_bridge

UNIMPLEMENTED art_portable_imt_conflict_trampoline
